### PR TITLE
PackageInstall: check if semver constraints are nil 

### LINKED ISSUE #740: PackageInstall CR without versionSelection section causes panic
**What steps did you take:**
Given the following **invalid** CR

```yaml
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: test
spec:
  serviceAccountName: kapp
  packageRef:
    refName: test-package.example.com
    version: 1.0.0
```

**What happened:**
The kapp-controller `Pod` crashed with a `SIGSEGV`

```plain
kapp-controller panic: runtime error: invalid memory address or nil pointer dereference                                                                       
kapp-controller [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1a4a72b]                                                                       
kapp-controller                                                                                                                                               
kapp-controller goroutine 971 [running]:                                                                                                                      
kapp-controller github.com/vmware-tanzu/carvel-kapp-controller/pkg/packageinstall.(*PackageInstallCR).referencedPkgVersion(_)                                 
kapp-controller     github.com/vmware-tanzu/carvel-kapp-controller/pkg/packageinstall/packageinstall.go:229 +0x22b                                            
kapp-controller github.com/vmware-tanzu/carvel-kapp-controller/pkg/packageinstall.(*PackageInstallCR).reconcile(0xc000cc4a50, 0xc000d51be0)                   
kapp-controller     github.com/vmware-tanzu/carvel-kapp-controller/pkg/packageinstall/packageinstall.go:105 +0x498                                            
kapp-controller github.com/vmware-tanzu/carvel-kapp-controller/pkg/packageinstall.(*PackageInstallCR).Reconcile(0xc000cc4a50)                                 
kapp-controller     github.com/vmware-tanzu/carvel-kapp-controller/pkg/packageinstall/packageinstall.go:71 +0x12f                                             
kapp-controller github.com/vmware-tanzu/carvel-kapp-controller/pkg/packageinstall.(*Reconciler).Reconcile(0xc00009cf50, {0x2322cd0, 0xc00081a420}, {{{0xc00093
kapp-controller     github.com/vmware-tanzu/carvel-kapp-controller/pkg/packageinstall/reconciler.go:81 +0x305                                                 
kapp-controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc000814320, {0x2322cd0, 0xc00081a390}, {{{0xc0009357d0?, 0x1e
kapp-controller     sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:114 +0x222                                                   
kapp-controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000814320, {0x2322c28, 0xc000852a00}, {0x1d88dc0?, 0x
kapp-controller     sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:311 +0x2e9                                                   
kapp-controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000814320, {0x2322c28, 0xc000852a00})             
kapp-controller     sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:266 +0x1d9                                                   
kapp-controller sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()                                                          
kapp-controller     sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:227 +0x85                                                    
kapp-controller created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2                                                   
kapp-controller     sigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:223 +0x309 
```

**What did you expect:**
I expected the `PackageInstall` to fail to reconcile, but for the `Pod` to stay healthy in the process. As it stands now, an invalid `PackageInstall` can prevent all `kapp-controller` functionality, effectively acting as a Denial-of-Service attack.

**Anything else you would like to add:**
Nothing additional.

**Environment:**

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`):
```yaml
kbld.k14s.io/images: |
  - origins:
    - local:
        path: /home/runner/work/carvel-kapp-controller/carvel-kapp-controller
    - git:
        dirty: false
        remoteURL: https://github.com/vmware-tanzu/carvel-kapp-controller
        sha: e0d5ff2821bc65ba2cbe11077b51e87135c96b24
        tags:
        - v0.38.1
    url: ghcr.io/vmware-tanzu/carvel-kapp-controller@sha256:a6cd018f365ab138ebc9f7d414513ec26418ce35b1ce3e8efe644ee1ab513f3a
```
- Kubernetes version (use `kubectl version`)
```plain
$ kubectl version                                                                             
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.9-eks-a64ea69", GitCommit:"540410f9a2e24b7a2a870ebfacb3212744b5f878", GitTreeState:"clean", BuildDate:"2022-05-12T19:15:31Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by joe-kimmel-vmw**
so we error instead of panic

<!--  Thanks for sending a pull request!  Here are some tips for you:

If this is your first time, please read our contributor guidelines: https://github.com/vmware-tanzu/carvel-kapp-controller/blob/develop/CONTRIBUTING.md and developer guide https://github.com/vmware-tanzu/carvel-kapp-controller/blob/develop/docs/dev.md
-->

#### What this PR does / why we need it:

fixes #740 

#### Which issue(s) this PR fixes:
<!--
If no issue exists for this change, please create an issue and link it here.
-->
Fixes # https://github.com/vmware-tanzu/carvel-kapp-controller/issues/740

#### Does this PR introduce a user-facing change?
Before this change:

1. copy example PKGI given in #740 into a file `borken.yml` 
2. run  `kapp deploy -a test -f borken.yml`

Observed behavior: kapp keeps polling for status, and there is a segfault in the kapp-controller logs. 

After this change: 
```
➜  ~ kapp deploy -a borken -f tmp-pkgi.yaml                                                                                                                                                                                                          [15/06/22|10:00AM]
Target cluster 'https://192.168.64.8:8443' (nodes: minikube)

Changes

Namespace  Name  Kind            Age  Op  Op st.  Wait to    Rs    Ri
default    test  PackageInstall  41m  -   -       reconcile  fail  Reconcile failed:  (message: unable
                                                                   to find valid semver version
                                                                   selection in PackageInstall test)

Op:      0 create, 0 delete, 0 update, 1 noop, 0 exists
Wait to: 1 reconcile, 0 delete, 0 noop

Continue? [yN]: y

10:35:47AM: ---- applying 1 changes [0/1 done] ----
10:35:47AM: noop packageinstall/test (packaging.carvel.dev/v1alpha1) namespace: default
10:35:47AM: ---- waiting on 1 changes [0/1 done] ----
10:35:47AM: fail: reconcile packageinstall/test (packaging.carvel.dev/v1alpha1) namespace: default
10:35:47AM:  ^ Reconcile failed:  (message: unable to find valid semver version selection in PackageInstall test)

kapp: Error: waiting on reconcile packageinstall/test (packaging.carvel.dev/v1alpha1) namespace: default:
  Finished unsuccessfully (Reconcile failed:  (message: unable to find valid semver version selection in PackageInstall test))
  ```


#### Additional Notes for your reviewer:

##### Review Checklist:

- [ ] Follows the [developer guidelines](https://carvel.dev/shared/docs/latest/development_guidelines/)
- [ ] Relevant tests are added or updated
- [ ] Relevant docs in this repo added or updated
- [ ] Relevant carvel.dev docs added or updated in a separate PR and there's
  a link to that PR
- [ ] Code is at least as readable and maintainable as it was before this
  change

#### Additional documentation e.g., Proposal, usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/packageinstall/packageinstall.go [hunk 1]
```diff
@@ -207,6 +207,9 @@ func (pi *PackageInstallCR) referencedPkgVersion() (datapkgingv1alpha1.Package,
 	}
 
 	semverConfig := pi.model.Spec.PackageRef.VersionSelection
+	if semverConfig == nil {
+		return datapkgingv1alpha1.Package{}, fmt.Errorf("unable to find valid semver version selection in PackageInstall %s", pi.model.Name)
```
Comment (cppforlife) [inline pkg/packageinstall/packageinstall.go]: - carvel errors start capitalized
- no need to include "in PackageInstall %s", pi.model.Name" since error is already in context of specific PackageInstall.
- "unable to find valid semver version selection" may be interpreted that package version cannot be found, may be rephrase as "Expected non-empty version selection"

as a side note, @benmoss added a validation section for fields. should we use it?

Comment (joe-kimmel-vmw) [reply pkg/packageinstall/packageinstall.go]: hmm do you think [our docs are wrong](https://carvel.dev/kapp-controller/docs/v0.38.0/packaging/#package-install)?

```
    # Selects version of a package based on constraints provided (optional)
    # Either version or versionSelection is required.
    versionSelection:
      # Constraint to limit acceptable versions of a package;
      # Latest version satisfying the constraint is chosen;
      # Newly available, acceptable later versions are picked up and installed automatically. (optional)
      constraints: ">v1.5.3"
      # Include prereleases when selecting version. (optional)
      prereleases: {}
      ```

Comment (cppforlife) [reply pkg/packageinstall/packageinstall.go]: > Either version or versionSelection is required.

yup, they seem to be mentioning older API design, when we had `version` sibling field. i dont think we kept it.

Comment (joe-kimmel-vmw) [reply pkg/packageinstall/packageinstall.go]: docs fix, applied across all versions:  https://github.com/vmware-tanzu/carvel/pull/462
