### PR TITLE
Fix error handling in package release cli

### LINKED ISSUE #1552: Fix error handling in kctrl package release command
**What steps did you take:**
```
❯ kctrl package release --chdir "carvel-packages/my-package-name" --version "0.0.1" --yes --repo-output ../../package-repository

[...skipped...]
Building images and resolving references
	    | $ ytt -f /var/folders/t2/ypy2b3v55g163rqdg934k2pr0000gp/T/kapp-controller-fetch-template-[...skipped...]
An imgpkg bundle consists of all required manifests bundled into an OCI image.
This image is pushed to a registry and consumed by the package.
Pushing imgpkg bundle
	    | $ imgpkg push -b [...skipped...]:build-1714175591 -f ./bundle-[...skipped...]:build-1714175591-2627758157 --tty=true
	    | dir: .
	    | dir: .imgpkg
	    | file: .imgpkg/images.yml
[...skipped...]
	    | Pushed '[...skipped...]@sha256:4525b5ee06.......41dcf7801'
	    | Succeeded

Succeeded

❯ ls package-repository/
pkgrepo-build.yml
```

**^^^ No package content**

**What happened:**
`kctrl package release ... --repo-output ...`  command is silently ignoring errors from releaseResources function.
Say, if incompatible ytt version is installed, this command will not yield any errors but no content will be written to the destination.

**What did you expect:**
Expected error in this specific environment:

```
	    | Succeeded

kctrl: Error: exit status 1: ytt:
  Error: unknown flag: --data-values-schema-inspect
```
**Anything else you would like to add:**
n/a

**Environment:**
n/a

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by goshkis**
#### What this PR does / why we need it:
`kctrl package release ... --repo-output ...`  command is silently ignoring errors from releaseResources function.
Say, if incompatible ytt version is installed, this command will not yield any errors but no content will be written to the destination.

The bug seems to be in a simple mistake unconditionally returning nil in case of any errors
 
#### Which issue(s) this PR fixes:

Fixes https://github.com/carvel-dev/kapp-controller/issues/1552

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

##### Review Checklist:

- [ ] Follows the [developer guidelines](https://carvel.dev/shared/docs/latest/development_guidelines/)
- [ ] Relevant tests are added or updated
- [ ] Relevant docs in this repo added or updated
- [ ] Relevant carvel.dev docs added or updated in a separate PR and there's
  a link to that PR
- [ ] Code is at least as readable and maintainable as it was before this
  change

#### Additional documentation e.g., Proposal, usage docs, etc.:

```docs

```

### CODE REVIEW

File: cli/pkg/kctrl/cmd/package/release/release.go [hunk 1]
```diff
@@ -134,7 +134,7 @@ func (o *ReleaseOptions) Run() error {
 		case release.Resource != nil:
 			err = o.releaseResources(appSpec, *pkgBuild, &pkgConfigs.Pkgs[0], &pkgConfigs.PkgMetadatas[0])
 			if err != nil {
-				return nil
+				return err
 			}
```
Comment (praveenrewar) [inline cli/pkg/kctrl/cmd/package/release/release.go:138]: nit: We can just do a return directly
```go
return o.releaseResources(appSpec, *pkgBuild, &pkgConfigs.Pkgs[0], &pkgConfigs.PkgMetadatas[0])
```

**Review by praveenrewar — COMMENTED** [review]
Thank you so much for the fix @goshkis!
Do you think you would be able to add a test for this?

**Comment by goshkis** [comment]
> Thank you so much for the fix @goshkis! Do you think you would be able to add a test for this?

I looked at the tests in the repo, and think this will take some time for me to understand how to add the new test properly.
Unfortunately, I don't have time for this now.

File: cli/pkg/kctrl/cmd/package/release/release.go (hunk 1 above)
Comment (goshkis) [reply cli/pkg/kctrl/cmd/package/release/release.go:138]: It's not the last call in the Run(), so proposed change will skip o.printNextSteps() below.

Comment (rohitagg2020) [reply cli/pkg/kctrl/cmd/package/release/release.go:138]: @goshkis We shouldn't be printing the next steps if `error` is encountered. 
Apart from this change, LGTM

**Comment by rohitagg2020** [comment]
> > Thank you so much for the fix @goshkis! Do you think you would be able to add a test for this?
> 
> I looked at the tests in the repo, and think this will take some time for me to understand how to add the new test properly. Unfortunately, I don't have time for this now.

We are ok with skipping the test for now

**Review by rohitagg2020 — APPROVED** [review]

**Review by praveenrewar — APPROVED** [review]
