### PR TITLE
Handle when a PackageInstall values have no SecretRef

### LINKED ISSUE #603: empty PackageInstall values ref cause nil deref error
**What steps did you take:**
user believes that they have configured one of the PackageInstalls with empty values ref e.g.

```
spec:
  values:
  - {}
```

**What happened:**
```
{"level":"info","ts":1649171226.2686238,"logger":"kc.controller.handler","msg":"enqueueing PackageInstallList"}
E0405 15:07:06.328565      17 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1234 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x19d3180, 0x2dd41a0})
	k8s.io/apimachinery@v0.19.15/pkg/util/runtime/runtime.go:74 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00131b0c0})
	k8s.io/apimachinery@v0.19.15/pkg/util/runtime/runtime.go:48 +0x75
panic({0x19d3180, 0x2dd41a0})
	runtime/panic.go:1038 +0x215
github.com/vmware-tanzu/carvel-kapp-controller/pkg/packageinstall.NewApp(_, _, {{{0xc001003827, 0x7}, {0xc001273380, 0x22}}, {{0xc0012733b0, 0x26}, {0x0, 0x0}, ...}, ...})
	github.com/vmware-tanzu/carvel-kapp-controller/pkg/packageinstall/app.go:162 +0xc1d
github.com/vmware-tanzu/carvel-kapp-controller/pkg/packageinstall.(*PackageInstallCR).reconcileAppWithPackage(_, _, {{{0xc001003827, 0x7}, {0xc001273380, 0x22}}, {{0xc0012733b0, 0x26}, {0x0, 0x0}, ...}, ...})
	github.com/vmware-tanzu/carvel-kapp-controller/pkg/packageinstall/packageinstall.go:173 +0x165
github.com/vmware-tanzu/carvel-kapp-controller/pkg/packageinstall.(*PackageInstallCR).reconcile(0xc000ba4370, 0xc001341aa8)
	github.com/vmware-tanzu/carvel-kapp-controller/pkg/packageinstall/packageinstall.go:150 +0x751
github.com/vmware-tanzu/carvel-kapp-controller/pkg/packageinstall.(*PackageInstallCR).Reconcile(0xc000ba4370)
	github.com/vmware-tanzu/carvel-kapp-controller/pkg/packageinstall/packageinstall.go:70 +0x13e
github.com/vmware-tanzu/carvel-kapp-controller/pkg/packageinstall.(*Reconciler).Reconcile(0xc000409a90, {0x1f27a38, 0xc000d5a4e0}, {{{0xc000a13eb0, 0x1aa22e0}, {0xc000a13ea0, 0xc00119a0c0}}})
	github.com/vmware-tanzu/carvel-kapp-controller/pkg/packageinstall/reconciler.go:81 +0x305
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00076fa40, {0x1f27990, 0xc0009a01c0}, {0x1a66680, 0xc00131b0c0})
	sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263 +0x303
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00076fa40, {0x1f27990, 0xc0009a01c0})
	sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1({0x1f27990, 0xc0009a01c0})
	sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198 +0x46
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
```

**What did you expect:**
an error within PackageInstall status that values ref cannot be empty.

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Environment:**

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`):
- Kubernetes version (use `kubectl version`)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by benmoss**
#### What this PR does / why we need it:
Validate that PackageInstalls `spec.values` must have a `secretRef`. 
#### Which issue(s) this PR fixes:

Fixes #603 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/packageinstall/packageinstall.go [hunk 1]
```diff
@@ -74,14 +75,28 @@ func (pi *PackageInstallCR) Reconcile() (reconcile.Result, error) {
...
 		return reconcile.Result{Requeue: true}, statusErr
 	}
 
 	return result, err
 }
 
+// Validate returns an aggregated error if any fields on the underlying PackageInstall are invalid
+func (pi *PackageInstallCR) Validate() error {
+	var allErrs field.ErrorList
+	for i, value := range pi.model.Spec.Values {
```
Comment (joe-kimmel-vmw) [inline pkg/packageinstall/packageinstall.go]: if we're just checking SecretRef this feels like the right approach,  but given the slightly aspirational comment description "...any fields..." I was getting ready for some more generalized like, openAPI style validation.     Then i  confused myself b/c in https://github.com/vmware-tanzu/carvel-kapp-controller/blob/develop/config/crds.yml it looks like SecretRef is a field on Package, not PackageInstall.   What do you think?

Comment (neil-hickey) [reply pkg/packageinstall/packageinstall.go]: I see it on the PKGI @joe-kimmel-vmw https://carvel.dev/kapp-controller/docs/v0.34.0/packaging/#package-install

`spec.values` near the bottom

---

I 👍 to the - should this be a validation of many fields vs just the one specific field.

Comment (joe-kimmel-vmw) [reply pkg/packageinstall/packageinstall.go]: 🤦 oh yeah, [ here it is](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/develop/config/crds.yml#L1274)

File: pkg/packageinstall/reconciler.go [hunk 2]
```diff
@@ -78,5 +80,18 @@ func (r *Reconciler) Reconcile(ctx context.Context, request reconcile.Request) (
...
+	if err := pkgi.Validate(); err != nil {
+		pkgi.model.Status.FriendlyDescription = "Invalid"
+		pkgi.model.Status.UsefulErrorMessage = err.Error()
+		pkgi.model.Status.Conditions = []v1alpha1.AppCondition{{
+			Type:   kappctrlv1alpha1.ReconcileFailed,
+			Status: corev1.ConditionTrue,
+		}}
+		if err := pkgi.UpdateStatus(); err != nil {
+			return reconcile.Result{Requeue: true}, err
+		}
```
Comment (cppforlife) [inline pkg/packageinstall/reconciler.go]: instead of modifying private model on pkgi and exposing UpdateStatus(), i think it would be better to make a new public method on PackageInstallCR that modifies state and updates status e.g.

```
func (pi *PackageInstallCR) UpdateAsReconcileFailed(err error) error
```

wdyt?

File: pkg/packageinstall/packageinstall.go (hunk 1 above)
Comment (benmoss) [reply pkg/packageinstall/packageinstall.go]: Yeah, I think we're doing some validation mixed into other places right now, we don't have a centralized pattern. I was hoping this might be good a good pattern we could spread to other places.

File: pkg/packageinstall/reconciler.go (hunk 2 above)
Comment (benmoss) [reply pkg/packageinstall/reconciler.go]: Not crazy about that idea, `UpdateAsReconcileFailed` seems an overly specific method. I was trying to have the `Validate` method be more of a pure data model type method, but right now the `PackageInstall` is more of a delegated reconciler/controller object, with it doing all the client creates/updates. 

I think I see two options:
- move validate to be called by pkgi.Reconcile
- move UpdateStatus to outside Reconcile and have Validate update status

I think I prefer the first one just because it's more in line with the rest of the reconcilers and I don't want to boil the ocean, but I think I prefer the second one in the larger scheme of things, it reminds me that in Knative their reconciler framework automatically updates status after objects are reconciled
