### PR TITLE
Refresh package install after pausing it during updation

### LINKED ISSUE #924: `kctrl`: Updating version and values-file at the same time for an installed package errors out
**What steps did you take:**
* Installed a specific version of a package and also provided values-file.
   - `kctrl package installed create -i test-pkg --package pkg.test.carvel.dev --version 2.0.0 --namespace test-ns --values-file values.yaml`
* Tried to update the package version along with the values-file
   - `kctrl package installed update -i test-pkg --package pkg.test.carvel.dev --version 3.0.0-rc.1 --namespace test-ns --values-file values_update.yaml`

**What happened:**
An error was thrown
```bash
Target cluster 'https://192.168.49.2:8443' (nodes: minikube)

7:32:34PM: Pausing reconciliation for package installation 'test-pkg' in namespace 'test-ns'
7:32:35PM: Updating secret 'test-pkg-test-ns-values'
7:32:35PM: Creating overlay secrets
7:32:35PM: Updating package install for 'test-pkg' in namespace 'test-ns'

kctrl: Error: Updating package 'test-pkg':
  Operation cannot be fulfilled on packageinstalls.packaging.carvel.dev "test-pkg": the object has been modified; please apply your changes to the latest version and try again
```

**What did you expect:**
Update to work successfully.

**Anything else you would like to add:**
The error is thrown when we try to update both package version and values at the same time, when we try to update just the package version or the values-file, it works fine.

**Environment:**

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`): v0.41.2
- kctrl version: v0.41.2
- Kubernetes version (use `kubectl version`): 1.25.0

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by praveenrewar**
#### What this PR does / why we need it:
Refresh package install after pausing it during updation. 
Pausing a package install causes a change in observedGeneration, due to this it needs to be refreshed to be able to update it later on.

#### Which issue(s) this PR fixes:

Fixes #924

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

##### Review Checklist:

- [x] Follows the [developer guidelines](https://carvel.dev/shared/docs/latest/development_guidelines/)
- [x] Relevant tests are added or updated
- [x] Relevant docs in this repo added or updated
- [x] Relevant carvel.dev docs added or updated in a separate PR and there's
  a link to that PR
- [x] Code is at least as readable and maintainable as it was before this
  change

#### Additional documentation e.g., Proposal, usage docs, etc.:

```docs

```

### CODE REVIEW

File: cli/pkg/kctrl/cmd/package/installed/create_or_update.go [hunk 1]
```diff
@@ -379,6 +377,20 @@ func (o CreateOrUpdateOptions) update(client kubernetes.Interface, kcClient kccl
 			return err
 		}
 		reconciliationPaused = true
+
+		// observedGeneration is updated after after pausing reconciliation
```
Comment (praveenrewar) [inline cli/pkg/kctrl/cmd/package/installed/create_or_update.go]:
```suggestion
		// observedGeneration is updated after pausing reconciliation
```

File: cli/test/e2e/package_install_test.go [hunk 2]
```diff
@@ -95,7 +104,10 @@ spec:
 	})
 
 	logger.Section("Installing test package", func() {
-		_, err := kappCtrl.RunWithOpts([]string{"package", "installed", "create", "--package-install", pkgiName, "-p", packageMetadataName, "--version", packageVersion1}, RunOpts{})
+		valuesFile := newTmpFile(t, "values-file", valuesFile1)
+		_, err := kappCtrl.RunWithOpts([]string{"package", "installed", "create", "--package-install", pkgiName,
+			"-p", packageMetadataName, "--version", packageVersion1,
+			"--values-file", valuesFile.Name()}, RunOpts{})
```
Comment (100mik) [inline cli/test/e2e/package_install_test.go]: Lets use stdin input for values file?

Comment (praveenrewar) [reply cli/test/e2e/package_install_test.go]: Yes, makes sense.

Comment (praveenrewar) [reply cli/test/e2e/package_install_test.go]: Done.

**Review by 100mik — APPROVED** [review]
LGTM!
