### PR TITLE
Fix panic calling `tanzu package installed status`

### LINKED ISSUE #1160: panic on `tanzu package installed status`
**What steps did you take:**
Run `tanzu package installed status` without any argument.

**What happened:**
The program panicked:
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/vmware-tanzu/carvel-kapp-controller/cli/pkg/kctrl/cmd/package/installed.(*StatusOptions).Run(0xc000126210?, {0x3969940?, 0xc000330240?, 0x39385a0?})
	/go/pkg/mod/github.com/vmware-tanzu/carvel-kapp-controller/cli@v0.0.0-20230106043644-ad24bdc3e412/pkg/kctrl/cmd/package/installed/status.go:64 +0x417
github.com/vmware-tanzu/carvel-kapp-controller/cli/pkg/kctrl/cmd/package/installed.NewStatusCmd.func1(0xc000033080?, {0x3969940?, 0xa?, 0xc00013eab3?})
	/go/pkg/mod/github.com/vmware-tanzu/carvel-kapp-controller/cli@v0.0.0-20230106043644-ad24bdc3e412/pkg/kctrl/cmd/package/installed/status.go:40 +0x25
github.com/vmware-tanzu/carvel-kapp-controller/cli/pkg/kctrl/cmd.configureGlobalFlags.func1.1(0x0?, {0x3969940, 0x0, 0x0})
	/go/pkg/mod/github.com/vmware-tanzu/carvel-kapp-controller/cli@v0.0.0-20230106043644-ad24bdc3e412/pkg/kctrl/cmd/kctrl.go:141 +0xce
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0x0?, {0x3969940, 0x0, 0x0})
	/go/pkg/mod/github.com/cppforlife/cobrautil@v0.0.0-20221130162803-acdfead391ef/misc.go:45 +0x6d
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0x0?, {0x3969940, 0x0, 0x0})
	/go/pkg/mod/github.com/cppforlife/cobrautil@v0.0.0-20221130162803-acdfead391ef/misc.go:45 +0x6d
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc00023bb80?, {0x3969940, 0x0, 0x0})
	/go/pkg/mod/github.com/cppforlife/cobrautil@v0.0.0-20221130162803-acdfead391ef/misc.go:45 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc00023bb80, {0x3969940, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000199400)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/vmware-tanzu/tanzu-framework/cli/runtime/plugin.(*Plugin).Execute(...)
	/go/src/cayman-tanzu-framework/tanzu-framework/src/cli/runtime/plugin/plugin.go:60
main.main()
	/go/src/cayman-tanzu-framework/tanzu-framework/src/cmd/cli/plugin/package/main.go:44 +0x92
```
**What did you expect:**
The program should provide a meaningful error message and exit properly.

**Environment:**

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`):
- Kubernetes version (use `kubectl version`)

Not applicable.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by clebs**
#### What this PR does / why we need it:
Calling `tanzu package installed status` without any arguments causes the program to panic (see linked issue).

#### Which issue(s) this PR fixes:
Fixes #1160

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

##### Review Checklist:

- [x] Follows the [developer guidelines](https://carvel.dev/shared/docs/latest/development_guidelines/)
- [x] Relevant tests are added or updated
- [x] Relevant docs in this repo added or updated
- [x] Relevant carvel.dev docs added or updated in a separate PR and there's
  a link to that PR
- [x] Code is at least as readable and maintainable as it was before this
  change

#### Additional documentation e.g., Proposal, usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

File: cli/pkg/kctrl/cmd/package/installed/status.go [hunk 1]
```diff
@@ -61,6 +61,9 @@ func NewStatusCmd(o *StatusOptions, flagsFactory cmdcore.FlagsFactory) *cobra.Co
 
 func (o *StatusOptions) Run(args []string) error {
 	if o.pkgCmdTreeOpts.PositionalArgs {
+		if len(args) == 0 {
+			return fmt.Errorf("Package name not provided.")
+		}
 		o.Name = args[0]
```
Comment (praveenrewar) [inline cli/pkg/kctrl/cmd/package/installed/status.go]: Good catch! 
Since we are already checking for the name on the next line, we could probably just do:
```suggestion
		if len(args) > 0 {
			o.Name = args[0]
		}
```

**Review by praveenrewar — COMMENTED** [review]
Thank you so much for finding and fixing this ❤️   
I just noticed that this issue is present in other commands as well, would you like to work on those as well?

File: cli/pkg/kctrl/cmd/package/installed/status.go (hunk 1 above)
Comment (clebs) [reply cli/pkg/kctrl/cmd/package/installed/status.go]: I am also fine with that approach. I usually find it more readable to fail fast and avoid `else` clauses.

But you are right that we can leverage the error reporting further down.

Comment (clebs) [reply cli/pkg/kctrl/cmd/package/installed/status.go]: Applied! PTAL.

**Comment by clebs** [comment]
Hi @praveenrewar,

thanks for the quick review! Yes I will do a swipe throughout the commands and see where this is happening.

Will submit another PR when ready linking to this issue.

**Review by praveenrewar — APPROVED** [review]
LGTM! Thank you so much!
