### PR TITLE
Fix app status diff, to ensure that deploy output is deduped

### LINKED ISSUE #1012: Deploy output while installing a package using kctrl is not deduped
**What steps did you take:**
Installed a package and observed output.

**What happened:**
The "Deploying" sections were repetitive.

**What did you expect:**
The deploy output should be diffed and only additional output since last update.

**Anything else you would like to add:**
Looks like how we diff app statuses regressed in #764 

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by 100mik**
#### What this PR does / why we need it:
It ensures that duplicate output is not printed while installing a Package.

#### Which issue(s) this PR fixes:

Fixes #1012 

#### Does this PR introduce a user-facing change?

```release-note
Fix: logs while tailing app statuses is verbose
```

##### Review Checklist:

- [x] Follows the [developer guidelines](https://carvel.dev/shared/docs/latest/development_guidelines/)
- [x] Relevant tests are added or updated
- [x] Relevant docs in this repo added or updated
- [x] Relevant carvel.dev docs added or updated in a separate PR and there's
  a link to that PR
- [x] Code is at least as readable and maintainable as it was before this
  change

#### Additional documentation e.g., Proposal, usage docs, etc.:

```docs

```

### CODE REVIEW

File: cli/pkg/kctrl/cmd/app/app_tailer.go [hunk 1]
```diff
@@ -49,7 +49,8 @@ func (o *AppTailer) printTillCurrent(status kcv1alpha1.AppStatus) error {
 		return nil
 	}
 
-	completed, err := NewAppStatusDiff(kcv1alpha1.AppStatus{}, status, o.statusUI).PrintUpdate()
+	completed, cachedDeployOutput, err := NewAppStatusDiff(kcv1alpha1.AppStatus{}, status, o.statusUI, o.lastSeenDeployStdout).PrintUpdate()
```
Comment (rohitagg2020) [inline cli/pkg/kctrl/cmd/app/app_tailer.go]: nit: rename `cachedDeployOutput` to `deployOutput`. Same everywhere

Comment (100mik) [reply cli/pkg/kctrl/cmd/app/app_tailer.go]: Makes sense, because it is not cached at this point! Will make the change.

Comment (100mik) [reply cli/pkg/kctrl/cmd/app/app_tailer.go]: Gonna wait for another review and do this change with other suggested changes

**Review by praveenrewar — APPROVED** [review]
LGTM (other than Rohit's comment).

**Comment by 100mik** [comment]
Made the change! Waiting for tests to go green
