### PR TITLE
Fix app-namespace usage for cluster options

### LINKED ISSUE #1332: Version 0.48.0 introduced bug/regression when installing using kubeconfig to separate cluster.
**What steps did you take:**

Using latest 0.48.0. This problem doesn't arise with 0.47.0.

Using `App` resources to install stuff into a separate cluster using a `kubeconfig`. Eg. something like:

```
metadata:
  name: vcluster-session-educates-cli-w03-s001
  namespace: educates-cli-w03
spec:
  cluster:
    kubeconfigSecretRef:
      key: config
      name: vc-shared-vcluster
    namespace: default
```

**What happened:**

The package will not be installed and fails with a message:

```
stderr: 'kapp: Error: namespaces "educates-cli-w03" not found'
stdout: 'Target cluster ''https://shared-vcluster.educates-cli-w03.svc.cluster.local/''(nodes: educates-control-plane)'
```

In other words, `kapp-controller` is now expecting a namespace with name the same as the namespace containing the `App` in the originating cluster, to exist in the target cluster, even though this should not be required.

In 0.47.0 there was no such requirement and everything worked fine.

Setting the new `defaultNamespace` property added in 0.48.0 doesn't workaround the regression.

**What did you expect:**

Should have worked like in 0.47.0 when using `kubeconfig` to install in a different cluster.

**Anything else you would like to add:**

Nope.

**Environment:**

- kapp Controller version: 0.48.0

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by praveenrewar**
#### What this PR does / why we need it:
During the introduction of defaultNamespace feature, we started using --app-namespace flag from kapp which should be used carefully when using cluster options instead of service account

The behaviour while using cluster options would be:
* If defaultNamespace is not used
   * kapp app and resources (if metadata.namespace is not provided) are created in cluster.Namespace if it is provided, or else the namespace from the kubeconfig is used.
* If defaultNamespace is provided
   * If cluster.Namespace is provided, then the kapp would be created there and the default namespace for the resources would be the defaultNamespace.
   * If clusterNamespace is not provided, then kapp app would be created in the kubeconfig namespace and the default namespace for the resources would be the defaultNamespace.
   
| `cluster.namespace` | `defaultNamespace` | desired behaviour | PR behaviour |
|----------------------|----------------------|-------------------|--------------|
| ✅                                 |                                     | meta: cluster.namespace, resources: cluster.namespace | Same as desired behaviour |
| ✅                                 | ✅                                | meta: cluster.namespace, resources: defaultNamespace | Same as desired behaviour |
|                                     | ✅                                | meta: kubeconfig namespace, resources: defaultNamespace |  Same as desired behaviour |
|                                     |                                  | meta: kubeconfig namespace, meta: kubeconfig namespace |  Same as desired behaviour|

TODO
- [x] Manual testing for the above scenarios.

#### Which issue(s) this PR fixes:

Fixes #1332

#### Does this PR introduce a user-facing change?

```release-note

```

##### Review Checklist:

- [ ] Follows the [developer guidelines](https://carvel.dev/shared/docs/latest/development_guidelines/)
- [ ] Relevant tests are added or updated
- [ ] Relevant docs in this repo added or updated
- [ ] Relevant carvel.dev docs added or updated in a separate PR and there's
  a link to that PR
- [ ] Code is at least as readable and maintainable as it was before this
  change

#### Additional documentation e.g., Proposal, usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e/kappcontroller/default_namespace_test.go [hunk 1]
```diff
@@ -71,6 +72,138 @@ spec:
...
+		kapp.Run([]string{"delete", "-a", name})
+		
+	}
+  cleanUpTargetCluster := func() {
+    kapp.RunWithOpts([]string{"delete", "-a", namespaceApp, "--kubeconfig", kubeconfigFile.Name()}, e2e.RunOpts{NoNamespace: true})
+  }
+	
+  cleanUp()
+  cleanUpTargetCluster()
+	defer cleanUp()
```
Comment (neil-hickey) [inline test/e2e/kappcontroller/default_namespace_test.go:109]: something funky going on with indentation in this file.

**Review by neil-hickey — APPROVED** [review]
LGTM, it's honestly quite confusing overall, not the PR but our general code flow because of all the scenarios. The tests nicely illustrate it, but the code is ... rough. Happy to refactor later on at some point.

File: test/e2e/kappcontroller/default_namespace_test.go (hunk 1 above)
Comment (praveenrewar) [reply test/e2e/kappcontroller/default_namespace_test.go:109]: Good catch! I am not sure how this happened and why build.sh didn't fix it. I will fix it.
