### PR TITLE
only inspect if deployment attempted

### LINKED ISSUE #77: Don't run kapp inspect if we haven't successfully deployed
**What steps did you take:**
1. Deploy an app that has a failing fetch stage:
```yaml
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: simple-app
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  fetch:
  - http:
      url: i-dont-exist
  template:
  - ytt: {}
  deploy:
  - kapp: {}
```
2. `kubectl get apps -n <namespace you deployed to> -oyaml`
3. see that status has an inspect stage showing an error

**What happened:**
Seeing the inspect error, which isnt the actual error causing reconciliation to fail, is misleading
```yaml
    fetch:
      error: 'Fetching resources: exit status 1'
      exitCode: 1
      startedAt: "2021-01-27T19:33:30Z"
      stderr: |
        Error: Syncing directory '0': Syncing directory '.' with HTTP contents: Downloading URL: Initiating URL download: Get i-dont-exist: unsupported protocol scheme ""
      updatedAt: "2021-01-27T19:33:30Z"
    friendlyDescription: 'Reconcile failed: Fetching resources: exit status 1'
    inspect:
      error: 'Inspecting: exit status 1'
      exitCode: 1
      stderr: 'kapp: Error: App ''simple-app-ctrl'' (namespace: default) does not
        exist: configmaps "simple-app-ctrl" not found'
      stdout: Target cluster 'https://10.96.0.1:443'
      updatedAt: "2021-01-27T19:33:30Z"
```

**What did you expect:**
To just see the error that relates to why the app is failing (in this case the fetch)

We should not run inspect if the app has never been deployed.

### PR DESCRIPTION
**Pull request by danielhelfand**
Closes #77

This pull requests adds skipping the inspect reconciliation in the event an app deployment is never attempted. Since the deployment is not attempted, adding inspect to the app status might distract users from the true error they are experiencing.

### CODE REVIEW

File: pkg/app/app_reconcile.go [hunk 1]
```diff
@@ -80,8 +80,11 @@ func (a *App) reconcileDeploy() error {
 	result := a.reconcileFetchTemplateDeploy()
 	a.setReconcileCompleted(result)
 
-	// Reconcile inspect regardless of deploy success
-	_ = a.reconcileInspect()
+	deployAttempted := a.Status().Deploy == nil
+	// Reconcile inspect regardless of deploy success but don't inspect if deploy never attempted
+	if !deployAttempted {
```
Comment (cppforlife) [inline pkg/app/app_reconcile.go]: other methods in this class use `a.app.Status...` so for consistency we should switch to `a.app.Status.Deploy`.

`a.app.Status.Deploy != nil` is descriptive enough imho for the conditional so var can be inlined.

File: test/e2e/fetch_test.go [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+
+import (
+	"fmt"
+	"reflect"
+	"strings"
+	"testing"
+
+	corev1 "k8s.io/api/core/v1"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+
```
Comment (cppforlife) [inline test/e2e/fetch_test.go]: nit: extra newline

File: pkg/app/app_reconcile.go (hunk 1 above)
Comment (danielhelfand) [reply pkg/app/app_reconcile.go]: Addressed

File: test/e2e/fetch_test.go (hunk 2 above)
Comment (danielhelfand) [reply test/e2e/fetch_test.go]: Addressed
