### PR TITLE
Check if pkgrs contain a packages directory

### LINKED ISSUE #760: Cryptic errors when using an invalid PackageRepository
**What steps did you take:**
Tried to create a PackageRepository that was actually not a PackageRepository bundle. Got this error:

```
NAME:          tbs-repository
VERSION:       2275761
REPOSITORY:    index.docker.io/ajitone/build-service
TAG:           1.5.2
STATUS:        Reconcile failed: Templating dir: Error (see .status.usefulErrorMessage for details)
REASON:        ytt: Error: Checking file '/etc/kappctrl-mem-tmp/kapp-controller-fetch-template-deploy759612810/0/packages': lstat /etc/kappctrl-mem-tmp/kapp-controller-fetch-template-deploy759612810/0/packages: no such file or directory
```

**What happened:**
I will fill in more details / better repro, just jotting this down now.

### PR DESCRIPTION
**Pull request by benmoss**
#### What this PR does / why we need it:
Fail more gracefully than ytt does if called on a non-existent `packages` directory if given an invalid PackageRepository fetch source

#### Which issue(s) this PR fixes:

Fixes #760 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/pkgrepository/app_template.go [hunk 1]
```diff
@@ -20,7 +22,19 @@ import (
 	sigsyaml "sigs.k8s.io/yaml"
 )
 
+var errInvalidPackageRepo = exec.NewCmdRunResultWithErr(fmt.Errorf("Invalid PackageRepository: must contain a packages directory"))
```
Comment (cppforlife) [inline pkg/pkgrepository/app_template.go]: how about:

```
Invalid package repository content: must contain 'packages/' directory but did not
```
