### PR TITLE
Enhance tty experience

### LINKED ISSUE #717: The "source <(kctrl completion bash)" command outputs an error message
**What steps did you take:**
[A clear and concise description steps and any files that can be used to reproduce the problem.]

Added `source <(kctrl completion bash)` to my `/etc/profile` so it would automatically load.

To reproduce the issue, you can simply run `source <(kctrl completion bash)`.

**What happened:**
[A small description of the result]

Got the following error message:

```text
Succeeded: command not found
```

This is because the `kctrl completion bash` commands outputs a `Succeeded` string at the end, which is not a valid command, and when used with `source`, bash tries to execute it.

Bash completion does work, though.

**What did you expect:**
[A description of what was expected]

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

As a workaround, I'm using the following:

```bash
source <(kctrl completion bash | grep -v Succeeded)
```

This removes the `Succeeded` string from the output, so the error doesn't occur.

Same issue has also occurred with kapp before, as I described here:
https://github.com/vmware-tanzu/carvel-kapp/issues/447
In kapp, this issue was fixed using the `--tty=false` option.

Same issue also occurs in imgpkg, as I described here:
https://github.com/vmware-tanzu/carvel-imgpkg/issues/342

This issue doesn't occur with ytt, because `ytt completion bash` doesn't output the `Succeeded` string.

**Environment:**

- kctrl version (use `kctrl --version`): `0.36.1`
- OS (e.g. from `/etc/os-release`): Using `Linux Ubuntu 20.04.4 LTS (Focal Fossa)` and `macOS Monterey 12.2.1`, but this issue occurs on any bash.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by praveenrewar**
#### What this PR does / why we need it:
- Set tty flag as an alternate/other flag instead of global flag.
- Set default value of tty to true for add/update, delete, pause, kick and status commands. For rest of the commands, default value should be false.

#### Which issue(s) this PR fixes:

Fixes #717 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

##### Review Checklist:

- [x] Follows the [developer guidelines](https://carvel.dev/shared/docs/latest/development_guidelines/)
- [ ] Relevant tests are added or updated
- [] Relevant docs in this repo added or updated
- [ ] Relevant carvel.dev docs added or updated in a separate PR and there's
  a link to that PR
- [x] Code is at least as readable and maintainable as it was before this
  change

#### Additional documentation e.g., Proposal, usage docs, etc.:

```docs

```

### CODE REVIEW

File: cli/pkg/kctrl/cmd/kctrl.go [hunk 1]
```diff
@@ -143,6 +144,20 @@ func ConfigureGlobalFlags(o *KctrlOptions, cmd *cobra.Command, flagsFactory cmdc
 	}
 }
 
+func ConfigureTTY(o *KctrlOptions, cmd *cobra.Command) {
```
Comment (cppforlife) [inline cli/pkg/kctrl/cmd/kctrl.go]: do we need to have this public?

Comment (praveenrewar) [reply cli/pkg/kctrl/cmd/kctrl.go]: Hmm, right, we can actually make the other function `ConfigureGlobal` private as well.

Comment (praveenrewar) [reply cli/pkg/kctrl/cmd/kctrl.go]: Done
