### PR TITLE
Wait for api server health when starting up

### LINKED ISSUE #180: Wait for apiserver to be healthy before continuing
**What steps did you take:**
Deploy kapp-controller with api server

**What happened:**
kapp-controller pod occasionally fails to start with the log message:
```
{"level":"error","ts":1619613871.5317369,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"Package.package.carvel.dev","error":"no matches for kind \"Package\" in version \"package.carvel.dev/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k...
```

This indicates we tried to start the controller runtime manager before the api server had successfully started and registered its resources.

**What did you expect:**
kapp-controller to always start up successfully

**Anything else you would like to add:**
Dont just sleep

**Environment:**

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`): v0.19.0-alpha.6
- Kubernetes version (use `kubectl version`): Doesn't matter

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by ewrenn8**
Closes #180

### CODE REVIEW

File: pkg/apiserver/apiserver.go [hunk 1]
```diff
@@ -102,18 +105,50 @@ func NewAPIServer(clientConfig *rest.Config) (*APIServer, error) {
...
+		if err != nil {
+			return fmt.Errorf("checking readiness: %v", err)
+		}
+
+		if ready {
+			return nil
+		}
+	}
+	return fmt.Errorf("timedout after %s waiting for api server to become healthy", startupTimeout)
+
```
Comment (danielhelfand) [inline pkg/apiserver/apiserver.go]: Nit: extra line

File: pkg/apiserver/apiserver.go [hunk 2]
```diff
@@ -102,18 +105,50 @@ func NewAPIServer(clientConfig *rest.Config) (*APIServer, error) {
...
+		ready, err := as.isReady()
+		if err != nil {
+			return fmt.Errorf("checking readiness: %v", err)
+		}
+
+		if ready {
+			return nil
+		}
+	}
+	return fmt.Errorf("timedout after %s waiting for api server to become healthy", startupTimeout)
```
Comment (danielhelfand) [inline pkg/apiserver/apiserver.go]:
```suggestion
	return fmt.Errorf("timed out after %s waiting for api server to become healthy", startupTimeout)
```

File: pkg/apiserver/apiserver.go [hunk 3]
```diff
@@ -102,18 +105,50 @@ func NewAPIServer(clientConfig *rest.Config) (*APIServer, error) {
...
 // Spawns go routine that exits when apiserver is stopped
-func (as *APIServer) Run() {
+func (as *APIServer) Run() error {
+	const (
+		startupTimeout = 30 * time.Second
+	)
 	go as.server.PrepareRun().Run(as.stopCh)
+
+	// wait for apiservice to have healthy status
+	for t := time.Now().Add(startupTimeout); time.Now().Before(t); {
```
Comment (cppforlife) [inline pkg/apiserver/apiserver.go]: call me a n00b, but this loop read confusingly. can we pull out t out of it on its own line?

File: pkg/apiserver/apiserver.go [hunk 4]
```diff
@@ -29,6 +30,7 @@ import (
 
 	genericopenapi "k8s.io/apiserver/pkg/endpoints/openapi"
 	"k8s.io/klog"
+	v1 "k8s.io/kube-aggregator/pkg/apis/apiregistration/v1"
```
Comment (cppforlife) [inline pkg/apiserver/apiserver.go]: may be apiregv1?

File: pkg/apiserver/apiserver.go [hunk 5]
```diff
@@ -102,18 +105,50 @@ func NewAPIServer(clientConfig *rest.Config) (*APIServer, error) {
...
-func (as *APIServer) Run() {
+func (as *APIServer) Run() error {
+	const (
+		startupTimeout = 30 * time.Second
+	)
 	go as.server.PrepareRun().Run(as.stopCh)
+
+	// wait for apiservice to have healthy status
+	timeout := time.Now().Add(startupTimeout)
+	for time.Now().Before(timeout) {
```
Comment (cppforlife) [inline pkg/apiserver/apiserver.go]: i just noticed that this a hot loop (will make calls one after another). i think it might be worth switching this to a simple i++ loop doing <30 times, and time.Sleep(1) in beetween.

Comment (ewrenn8) [reply pkg/apiserver/apiserver.go]: Ah yea, good call

Comment (ewrenn8) [reply pkg/apiserver/apiserver.go]: Updated
